apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "serve-app.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "serve-app.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "serve-app.name" . }}
    spec:
      containers:
        - name: serve-api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 8000
          resources:
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
