apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "train-app.fullname" . }}
spec:
  template:
    spec:
      containers:
      - name: trainer
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        resources:
          limits:
            cpu: {{ .Values.resources.limits.cpu }}
            memory: {{ .Values.resources.limits.memory }}
      restartPolicy: Never
